# Generated by Django 2.2.12 on 2020-06-17 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamsApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
