# Generated by Django 2.2.12 on 2020-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseau', models.CharField(max_length=255)),
                ('lien', models.URLField()),
                ('icones', models.CharField(choices=[('facebook', 'fa-facebook-f'), ('twitter', 'fa-twitte'), ('globe', 'fa-globe'), ('behance', 'fa-behance')], max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'réseau social',
                'verbose_name_plural': 'réseaux sociaux',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mapping',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='icones',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='mapping',
            field=models.URLField(null=True),
        ),
    ]
