# Generated by Django 2.2.12 on 2020-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='mapping',
            field=models.TextField(null=True),
        ),
    ]
