# Generated by Django 2.2.12 on 2020-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='banner',
            field=models.ImageField(null=True, upload_to='images/banner'),
        ),
    ]
